// Teste da API REST de Prestadores
@baseURL = http://localhost:4000/api/prestadores

// GET - Lista todos os prestadores
GET {{baseURL}}/?limit=10&skip=0
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0YmNiNmRlODQzM2I3MmVlYTFiYTdhIn0sImlhdCI6MTcxNjg0OTMyMywiZXhwIjoxNzE2OTM1NzIzfQ.isCo9fdfj0oSE7080ZT5WB9g-WGPBPZ5HcwGMJKfwjA

###
// GET - Lista o prestador pelo ID
GET {{baseURL}}/id/6639721466b5e6a6de9aade6
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjYzOTVmMDZiZGIxYTQyMzcyMGRjZmEyIn0sImlhdCI6MTcxNTAzNzIwMywiZXhwIjoxNzE1MTIzNjAzfQ.l76Ccoiw-_2ZfYD23SYfrGiD-1_CifmbKC0Edch-2UI


###
// GET - Lista o prestador pela razão social ou fantasia
GET {{baseURL}}/razao/boy
Content-Type: application/json

###
// DELETE - Remove o prestador pelo id
DELETE {{baseURL}}/665509fa62fb1707223125b8
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0YmNiNmRlODQzM2I3MmVlYTFiYTdhIn0sImlhdCI6MTcxNjg0OTMyMywiZXhwIjoxNzE2OTM1NzIzfQ.isCo9fdfj0oSE7080ZT5WB9g-WGPBPZ5HcwGMJKfwjA


###
// POST - Insere um novo prestador
POST {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0YmNiNmRlODQzM2I3MmVlYTFiYTdhIn0sImlhdCI6MTcxNjI0NjI3NiwiZXhwIjoxNzE2MzMyNjc2fQ.mXVnvoGR2keT-FZVGvGsiW3uGT9CToZw10Yq5GtVPvo

{
    "cnpj": "12345345000174",
    "razao_social": "JOSÉ LOPES TRANSPORTES LTDA.",
    "cep": "13310169",
    "endereco": {"logradouro": "Av. Presidente Kennedy, 321",
                "complemento": "",
                "bairro": "Centro",
                "localidade": "Votorantim",
                "uf": "SP"},
    "cnae_fiscal": 451510,
    "nome_fantasia": "ALCINA",
    "data_inicio_atividade": "2022-07-22",
    "localizacao": {
        "type": "Point",
        "coordinates": [-23.2904, -47.2963]
    }
}

###
// PUT - Altera um prestador já existente

PUT {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY0YmNiNmRlODQzM2I3MmVlYTFiYTdhIn0sImlhdCI6MTcxNjg0OTMyMywiZXhwIjoxNzE2OTM1NzIzfQ.isCo9fdfj0oSE7080ZT5WB9g-WGPBPZ5HcwGMJKfwjA

{
    "_id": "665509fa62fb1707223125b8",
    "cnpj": "45150718000143",
    "razao_social": "SERVIÇOS MOTOBOY LTDA. Alterado Novamente",
    "cep": "13310160",
    "endereco": {
      "logradouro": "Avenida Caetano Ruggieri",
      "complemento": "de 2011/2012 a 3791/3792",
      "bairro": "Parque Nossa Senhora da Candelária",
      "localidade": "Itu",
      "uf": "SP"
    },
    "cnae_fiscal": 451510,
    "nome_fantasia": "ELI MOTOBOY",
    "data_inicio_atividade": "2024-08-31",
    "localizacao": {
      "type": "Point",
      "coordinates": [
        -23.2904,
        -47.2963
      ]
    }
  }